DROP DATABASE db;

CREATE DATABASE db;

USE db;

CREATE TABLE nutricionista(
id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(120) NOT NULL,
senha VARCHAR(120) NOT NULL,
CRN VARCHAR(120) NOT NULL,
email VARCHAR(120) not null,
PRIMARY KEY(id)
);

CREATE TABLE usuario(
id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(120) NOT NULL,
email VARCHAR(120) NOT NULL,
senha VARCHAR(120) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE ingredientes(
id INT NOT NULL AUTO_INCREMENT,
descrição VARCHAR(120) NOT NULL,
calorias FLOAT NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE cardapio(
id INT NOT NULL AUTO_INCREMENT,
tipo VARCHAR(120) NOT NULL,
data DATE NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE item(
id INT NOT NULL AUTO_INCREMENT,
descrição VARCHAR(120) NOT NULL,
calorias FLOAT NOT NULL,
PRIMARY KEY(id)
);