CREATE DATABASE db;

USE db;

CREATE TABLE nutricionista(
id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(120) NOT NULL,
senha VARCHAR(120) NOT NULL,
CRN VARCHAR(120) NOT NULL,
email VARCHAR(120) not null,
PRIMARY KEY(id)
);

CREATE TABLE usuario(
id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(120) NOT NULL,
email VARCHAR(120) NOT NULL,
senha VARCHAR(120) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE cardapio(
id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(120) NOT NULL,
tipo VARCHAR(120) NOT NULL,
data DATE NOT NULL,
cardapio VARCHAR(600) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE ingredientes(
id INT NOT NULL AUTO_INCREMENT,
descricao VARCHAR(120) NOT NULL,
calorias FLOAT NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE item(
id INT NOT NULL AUTO_INCREMENT,
descricao VARCHAR(120) NOT NULL,
calorias FLOAT NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE cardapioid(
    id INT NOT NULL AUTO_INCREMENT,
    iditem INT NOT NULL,
    idcardapio INT NOT NULL,
    PRIMARY KEY(id)
);

ALTER TABLE cardapioid ADD CONSTRAINT `fk_cardapio2` FOREIGN KEY ( iditem ) REFERENCES item ( `id` );
ALTER TABLE cardapioid ADD CONSTRAINT `fk_cardapio3` FOREIGN KEY ( idcardapio ) REFERENCES cardapio ( `id` );
